name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:  
    name: "Meu primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira action"
        run: echo "Hello World !!!"
      - name: "Minha segunda action"
        run: |  
          echo "Você criou o seu primeiro workflow !!!"
          echo "Parabéns"
      - name: "Script python"
        run: |
          var = "Hello World !!!"
          print(var)
        shell: python
  segundo-job:
    name: "Instalação do ambiente Node.js"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação da versão do Node.js atual"
        run: node --version
